### ISSUE TITLE
Fix or Remove taunts/props/29.wav

### ISSUE THREAD

**Issue by Jonpopnycorn** [Vinzuerio/ph-enhanced#1]
The taunt doesn't stop. It was alright when they had to get it Randomly, but now that they can choose it right off the back. On top of that they can just choose that taunt as many times as they want.

Imagine everyone in the Props Team selecting that taunt in the Taunt Menu. It would make that game cancerous to play.

**Comment by Vinzuerio** [comment]
It's been since PH and I know that will happen, going to fix soon
