### ISSUE TITLE
Can no longer crouch-jump as a prop.

### ISSUE THREAD

**Issue by Pyroglyph** [Vinzuerio/ph-enhanced#10]
We used to be able to crouch-jump as props to reach nice places. Now this seems to have been removed. This seriously inhibits prop movement as any prop can barely jump up 10cm.

**Comment by TheHyperDrive** [comment]
Set lower gravity. That's how I got around the low jump, and everyone loves it. sv_gravity 150 in server.cfg

**Comment by Vinzuerio** [comment]
Added prop's jump power so everyone can jump normally like hunter does.
