### ISSUE TITLE
Can't get mapvote to disable cs and de maps

### ISSUE THREAD

**Issue by TheHyperDrive** [Vinzuerio/ph-enhanced#11]
I have been trying to figure out how to disable the default cs and de maps for my server. I have tried going through your map vote and ulx's map vote to try and disable this. Is there a specific line i should be looking for?

**Comment by daunknownman2010** [comment]
Are you sure **mv_mapprefix** isn't working for you? Try **mv_mapprefix "ph_"** and change the level with **changelevel**.

**Comment by TheHyperDrive** [comment]
I have changed it, everywhere I've seen it, even in the server.cfg. I still get cs, de and even the test server popping up.

**Comment by Vinzuerio** [comment]
This may your MapVote addon.
If you had MapVote fretta-like addons installed, you have to get removed and delete "data/mapvote" folder.

This may get conflicted with it so your cs_ and de_ maps were shown in the list.

**Comment by TheHyperDrive** [comment]
I think I finally got it, just have to put mv_mapprefix "ph_" in every time the server is started or restarted and it works fine.
