### ISSUE TITLE
Round Timer gets stuck at 0

### ISSUE THREAD

**Issue by aplewis7** [Vinzuerio/ph-enhanced#12]
[Prop Hunt Enhanced V14d] addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:42: attempt to index upvalue 'teamPlayers' (a nil value)

  1. SetRoundResult - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:42

   2. SetRoundResult - addons/pointshop2/lua/ps2/modules/prophunt_integration/sv_prophunthooks.lua:92

    3. RoundEndWithResult - gamemodes/fretta/gamemode/round_controller.lua:167

     4. RoundTimerEnd - gamemodes/prop_hunt/gamemode/init.lua:348

      5. unknown - gamemodes/fretta/gamemode/round_controller.lua:137

 

Timer Failed! [RoundEndTimer][@gamemodes/fretta/gamemode/round_controller.lua (line 137)]

I get this error when the round ends, it will not keep going. It will freeze and get this error.
I don't have any custom map vote or anything. I have ulx admin.

**Comment by Vinzuerio** [comment]
You're trying to use Prop Hunt with Pointshop 2 intregation, which, At this moment Prop hunt Enhanced may not supported with Pointshop 2 addon. Try using standard pointshop see if it's solve the issue?
