### ISSUE TITLE
Disable player model select in F1 menu.

### ISSUE THREAD

**Issue by TheHyperDrive** [Vinzuerio/ph-enhanced#13]
Is there any way to disable the player model selector in the Help menu? Planning on setting up a server, can't have all them for free.

**Comment by Vinzuerio** [comment]
http://project.wolvindra.net/phe_faq/#game_ConVar_props

there is a CVar called "ph_use_custom_plmodel" to disable player model select. It also available under "Admin" tab and uncheck the "Allow custom models for Hunters?"

![admin_menu](https://cloud.githubusercontent.com/assets/11814682/21007641/539463c6-bd70-11e6-9f40-16c28f3a2ce4.jpg)

**Comment by Vinzuerio** [comment]
http://project.wolvindra.net/phe_faq/#game_ConVar_props

there is a CVar called "ph_use_custom_plmodel" to disable player model select. It also available under "Admin" tab and uncheck the "Allow custom models for Hunters?"

![admin_menu](https://cloud.githubusercontent.com/assets/11814682/21007641/539463c6-bd70-11e6-9f40-16c28f3a2ce4.jpg)

**Comment by TheHyperDrive** [comment]
alright thanks!
