### ISSUE TITLE
Can't figure out how to fix these Lua errors.

### ISSUE THREAD

**Issue by SuigetsuShinso** [Vinzuerio/ph-enhanced#14]
[Prop Hunt Enhanced V14d] gamemodes/fretta/gamemode/init.lua:181: attempt to call method 'PlayerSpawnAsSpectator' (a nil value)
  1. unknown - gamemodes/fretta/gamemode/init.lua:181

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't include file 'base\gamemode\cl_init.lua' (File not found) (<nowhere>)

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't Load Init Script: 'base/gamemode/cl_init.lua'

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't include file 'base\gamemode\cl_init.lua' (File not found) (@gamemodes/fretta/gamemode/shared.lua (line 70))

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't Load Init Script: 'base/gamemode/cl_init.lua'

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_init.lua:47: attempt to call method 'Initialize' (a nil value)
  1. Initialize - gamemodes/fretta/gamemode/cl_init.lua:47
   2. unknown - gamemodes/fretta/gamemode/cl_init.lua:47

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82
_______________________________________________________________________________________________________________

EDIT: List grew longer.

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't include file 'base\gamemode\cl_init.lua' (File not found) (<nowhere>)

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't Load Init Script: 'base/gamemode/cl_init.lua'

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't include file 'base\gamemode\cl_init.lua' (File not found) (@gamemodes/fretta/gamemode/shared.lua (line 70))

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:
Couldn't Load Init Script: 'base/gamemode/cl_init.lua'

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_init.lua:47: attempt to call method 'Initialize' (a nil value)
  1. Initialize - gamemodes/fretta/gamemode/cl_init.lua:47
   2. unknown - gamemodes/fretta/gamemode/cl_init.lua:47

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

[Rage Bro Chris|2|STEAM_0:0:21189471] Lua Error:

[ERROR] gamemodes/fretta/gamemode/cl_hud.lua:82: attempt to call method 'HUDPaint' (a nil value)
  1. HUDPaint - gamemodes/fretta/gamemode/cl_hud.lua:82
   2. unknown - gamemodes/fretta/gamemode/cl_hud.lua:82

**Comment by Vinzuerio** [comment]
It seems you were replacing the prop hunt enhanced's fretta with something else

**Comment by SuigetsuShinso** [comment]
I downloaded the master file from the github here, and never changed the Fretta. I also tried GMAD on the workshop version which didn't work either.

**Comment by Vinzuerio** [comment]
Hmm... there's another problem from your log:

1. Where did you extract them, specifically?
if you put the gamemodes folder on addons folder that won't work.

2, It seems your clientside HUD or something that overrids to fretta's cl_init.lua, did you use any custom addons?

**Comment by SuigetsuShinso** [comment]
I put the game modes in the game modes folder, the add-ons in addons, and I
have no custom addons installed yet because I haven't gotten the game mode
to work yet.

**Comment by Vinzuerio** [comment]
Here's what you can try:
server side:
- remove all of your legacy PHE addons, and redownload the new repo (current version is 14f, on master branch)
- make sure you put them correctly, addons, cfg, and gamemodes **must** be extracted under garrysmod/ folder

client side:
you can either use from workshop version or from this repository, with the exact installation method from serverside. Just to make sure that there is no other gamemodes installed (such as original prop hunt) in your garry's mod.

**Comment by SuigetsuShinso** [comment]
Alright, will try tomorrow, and message back when I do.
