### ISSUE TITLE
Taunting Errors

### ISSUE THREAD

**Issue by jtnicandro** [Vinzuerio/ph-enhanced#15]
[Prop Hunt Enhanced V14g] gamemodes/prop_hunt/gamemode/init.lua:310: attempt to perform arithmetic on global 'TAUNT_DELAY' (a nil value)
  1. unknown - gamemodes/prop_hunt/gamemode/init.lua:310

The error that shows in the consol when some someone tries to taunt

**Comment by Reigners** [comment]
Don't know much, but this did the trick...
in gamemodes\prop_hunt\gamemode open file "init.lua"
from line 305. to 324.

> function GM:ShowSpare1(pl)
> 	if GetConVar("ph_enable_custom_taunts"):GetBool() && GAMEMODE:InRound() then
> 		pl:ConCommand("ph_showtaunts")
> 	end
> 	
> 	if !GetConVar("ph_enable_custom_taunts"):GetBool() && GAMEMODE:InRound() && pl:Alive() && (pl:Team() == TEAM_HUNTERS || pl:Team() == TEAM_PROPS) && pl.last_taunt_time + TAUNT_DELAY <= CurTime() && #PROP_TAUNTS > 1 && #HUNTER_TAUNTS > 1 then
> 		repeat
> 			if pl:Team() == TEAM_HUNTERS then
> 				rand_taunt = table.Random(HUNTER_TAUNTS)
> 			else
> 				rand_taunt = table.Random(PROP_TAUNTS)
> 			end
> 		until rand_taunt != pl.last_taunt
> 		
> 		pl.last_taunt_time = CurTime() + TAUNT_DELAY
> 		pl.last_taunt = rand_taunt
> 		
> 		pl:EmitSound(rand_taunt, 100)
> 	end	
> end

**change to this**

> function GM:ShowSpare1(pl)
> 	if GetConVar("ph_enable_custom_taunts"):GetBool() && GAMEMODE:InRound() then
> 		pl:ConCommand("ph_showtaunts")
> 	end
> 	
> 	if !GetConVar("ph_enable_custom_taunts"):GetBool() && GAMEMODE:InRound() && pl:Alive() && (pl:Team() == TEAM_HUNTERS || pl:Team() == TEAM_PROPS) && pl.last_taunt_time + PHE.TAUNT_DELAY <= CurTime() && #PHE.PROP_TAUNTS > 1 && #PHE.HUNTER_TAUNTS > 1 then
> 		repeat
> 			if pl:Team() == TEAM_HUNTERS then
> 				rand_taunt = table.Random(PHE.HUNTER_TAUNTS)
> 			else
> 				rand_taunt = table.Random(PHE.PROP_TAUNTS)
> 			end
> 		until rand_taunt != pl.last_taunt
> 		
> 		pl.last_taunt_time = CurTime() + PHE.TAUNT_DELAY
> 		pl.last_taunt = rand_taunt
> 		
> 		pl:EmitSound(rand_taunt, 100)
> 	end	
> end

**Comment by jtnicandro** [comment]
Did not work for me. Still showing the same error.

**Comment by Vinzuerio** [comment]
Fixed, forgot to add PHE prefix table.

https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/prop_hunt/gamemode/init.lua#L310
https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/prop_hunt/gamemode/init.lua#L319
