### ISSUE TITLE
Crowbar no damage / disable halos on default / waiting for players

### ISSUE THREAD

**Issue by Backallystabber** [Vinzuerio/ph-enhanced#16]
Hello !
I noticed that when I try to hit props default model "kleiner" it does no damage. It's not a big issue , but still.
Also , is there a way to disable prop select halos by default ? in server config file I tried ph_cl_halos 0 , didn't work. So I type that everytime server starts in server console , kinda annoying.

And the biggest issue is that when 1 player joins , he automaticly spawns and plays the first round alone untill the timer runs out. only then the next raund starts...
Is there a way to add something like "waiting for players" or automatic raund start when another player joins ?

_Didn't change anything in gamemod files (except added taunts) and only edited server.cfg file
gamemod added on a fresh server without addons (only ulysses admin mod) and no errors appear in server console._

**Comment by Vinzuerio** [comment]
I'm trying to figure out for the Prop doesn't take damage to the player (which this caused by the lag compesation) and it might have to redirect the damage soon to the props, so it can be kill-able. I've also trying to figure out the waiting for players since this can be issue too like round being skipped and such.

also, _ph_cl_halos_ is client side. You can whether put on your autoexec.cfg or by doing a forced client-side command like `RunConsoleCommand('ph_cl_halos','0')` whenever player joins (after InitialSpawn)

I'll notify you about the Prop Damage issue as well as 'Waiting for Players' additional features when this fixed.

**Comment by Backallystabber** [comment]
Thanks for the respond.
I've noticed that problem with the crowbar applies only for small props or kleiner model it self, so that's is not the biggest prolems ever..

I really hope that you'll manage to come up with something for the "waiting for players" because it does skip the first round by message "Draw ! Everybody loses" , and then another round because sometimes only one player joins a team.
Remembered that there was such a thing as "waiting for players" in Murder GM , so I looked at the code to see how it runs , yet I couldn't manage to come up with anything on my own.

And thanks for giving a heads up that "ph_cl_halos" are client sided , added a runconsolecommand line , and works just fine.

**Comment by daunknownman2010** [comment]
@Backallystabber I've put through some code that will pause the rounds until there are enough players on each team to start a proper game. Expect it in PH:E v14h.

**Comment by Backallystabber** [comment]
Since this is still open..
It's amazing what you guys are doing and thank you all so much for your effort on this.
Waiting for v14h with excitement.

And wanted to ask a fast question,
is MapVote.Start() located or called from somewhere else but round_controller.lua ?
Because.. Changed it to one I use > lauched the server > It works for 1st map , but on 2nd it loads fretta mapvote again, yet in .lua it's still the one I use.
I don't have PH enhaced on subscribe list or anything , so I have no idea why it would reload the fretta one.

If you have any ideas that would be awesome , if not it's fine , fretta mapvote does the trick too.

**Comment by Vinzuerio** [comment]
I noticed that it also available in init.lua, I'll update the documentation.

Also the Commit 14H has been pushed. You can use the 'waiting for player' feature and the crowbar damage now applies to the props :)
