### ISSUE TITLE
Round Start when MapVote begin

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#20]
Hi ( Sry, bad english )

I don't think it's a bug but when i reach the 10th round, the map vote start and a new round begin...

Is it possible to do like the old prop hunt? When max round reached then nothing append except the map vote?

**Comment by Vinzuerio** [comment]
I actually noticed this too. This happen when the maximum round hits but the game time is still running.

like Example, if you still have 5 minutes remaining but you are in last round (Let's say you are on round 10 and Round End happens), it will trigger the MapVote. However if you reached the game time and also the round time already reached the hits, then the "Proper" round end happens.

I think I'll look forward for this to make sure this should end the game and trigger the mapvote instead have to stay with next round happen while the time remaining still exists.

**Comment by Vinzuerio** [comment]
Updated. Check on the main repository or Reclone the gamemode. it should fixes the problem for now
