### ISSUE TITLE
Pointshop 1 compatibility problem

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#21]
Hi,

There is a problem with the pointshop 1 skins.

When you're in Props, the skin appear like in the video.
Since the last update, you can shot them in all the skin, but before there was really difficult to kill a props because when we shot the skin, the prop wasn't taking damages.

https://www.youtube.com/watch?v=vzpMKtUSxbc

Best regards,

**Comment by Vinzuerio** [comment]
In your pointshop/lua/pointshop/items/playermodels/<all of your playermodels>.lua, open up with text editor and notice the **`ITEM:PlayerSetModel(ply)`**

Add the following line before `ply:SetModel(self.Model)` : 
`if ply:Team() == TEAM_PROPS then return end`

this should prevent props team to use playermodel, which causing the 'actual' player models are being set.

**Comment by lucas2107** [comment]
I'm trying, thanks

**Comment by Vinzuerio** [comment]
Nice!
Also, I don't think spectator would be needed since it never been declared under PlayerSetModel()
