### ISSUE TITLE
Rebind taunt key

### ISSUE THREAD

**Issue by Mr-Rippe** [Vinzuerio/ph-enhanced#25]
Is it possible to rebind the F3 taunt key? If so, what line(s) need to be changed in order to do so?

**Comment by Vinzuerio** [comment]
By default, the gamemode's taunt uses gm_showspare1 (F3) and +menu_context KeyBind detection (default: C) for custom taunt menu.

The code represet on init.lua @ 330, GM:ShowSpare1() and cl_tauntwindow.lua @ 140 for KeyBind hook.

Also, it is suggested that this more into request. if you're looking request I'd suggest to put this on pull request section.
