### ISSUE TITLE
Grey shadow under props

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#27]
Hi,

Since the 7 april, some players are reporting to me a bug.
There is, sometimes, a little grey shadow under the prop
Screens: http://prnt.sc/f4smjr http://prnt.sc/f4x879

Best regards,

**Comment by Vinzuerio** [comment]
Should be fixed on next v15 update.

**Comment by Vinzuerio** [comment]
Update:
Just found out that the "invisible" model for the prop actually cast shadows from projected texture.

I'm going to put a custom invisible texture to make sure it doesn't cast shadows on any lighting entities (including projected texture (flashlight) itself)

**Comment by Jonpopnycorn** [comment]
I don't know if this will fix it, but you can try to also add this to the Props Class [Entity:SetNoDraw](https://wiki.garrysmod.com/page/Entity/SetNoDraw)
pl:SetNoDraw(true)
That way it won't render the props model

**Comment by lucas2107** [comment]
Okey, I'm testing :)

**Comment by Jonpopnycorn** [comment]
@lucas2107 let me know if it fixes the problem.

**Comment by lucas2107** [comment]
@Jonpopnycorn not working, it freeze the camera when you spectate the prop in third person view.

**Comment by Jonpopnycorn** [comment]
@lucas2107 How about try adding [Entity:SetRenderMode](https://wiki.garrysmod.com/page/Entity/SetRenderMode) in the Props Class?

pl:SetRenderMode( RENDERMODE_NONE )

Add it after pl:SetColor( Color(255, 255, 255, 0))

**Comment by lucas2107** [comment]
Did you tried it?

**Comment by Jonpopnycorn** [comment]
@lucas2107 Here are the results http://imgur.com/a/0u8wZ

**Comment by lucas2107** [comment]
Okey, testing, I will sent you the reports from my staff/players :)

**Comment by lucas2107** [comment]
Then, It's working. Hunters don't see the shadow, but props see this: http://image.noelshack.com/fichiers/2017/22/1496535890-ph-school0000.jpg

**Comment by Jonpopnycorn** [comment]
Remove **pl:SetColor( Color(255, 255, 255, 0))** since it serves no purpose

I couldn't replicate the props seeing the cube shadow,  can you give a little more details on the new problem for example:
Is the hunter pointing the flashlight at you, or are you using the props flashlight to see your own shadow
Can another prop view your shadow?
etc.

**Comment by lucas2107** [comment]
- Hunters don't see the shadow
- This is not a shadow
- All props got this behind them, but, they don't see this on others props
