### ISSUE TITLE
Possible idea to fix getting stuck when turning into a prop

### ISSUE THREAD

**Issue by Jonpopnycorn** [Vinzuerio/ph-enhanced#3]
Give the player a brief prop collision immunity from the prop entity that they just turned into allowing that player to move away instead of being stuck.

**Comment by TheHyperDrive** [comment]
I have a simple unstuck command that respawns the player. Tried to use the one that "thinks" it's way out, but most often, people used it to glitch. Here's my code:
[http://pastebin.com/EgN67wbQ](url)

Thinking of adding a way to make the user invisible for 5 seconds, so they have a chance to rehide, but unsure if that's practical.

**Comment by Vinzuerio** [comment]
If this still a thing, there could be a bits change that warns a player before turning a prop, to make sure player has a 'room' before changing into a prop.
