### ISSUE TITLE
Auto taunt bug report

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#30]
Hi, there is a list of knows bugs for auto taunt system:

- Timer don't reset at the end of the round
- Hunters are taunting with same taunts as props
- When a prop taunt, the auto taunt timer don't reset

Best regards,

**Comment by Vinzuerio** [comment]
Try Reclone the gamemode and see if that fixes. It seems worked on my side.

See what files that has been changed from [this commit](https://github.com/Vinzuerio/ph-enhanced/commit/2c4eccf9de410a7000575c35a7c41b13f9428bc8) ?

If the bug persist, I and @Thundernerd will might have to investigate what caused to that happen

**Comment by lucas2107** [comment]
On my sever, I've just modified the files who was updated. I'm going to try without modifications on my dev server today ^^

**Comment by Thundernerd** [comment]
Please let us know the result of the test without your modifications. The issues you are describing should not happen (obviously), and I know what parts of code is in there to prevent these things.

**Comment by lucas2107** [comment]
Update:

Timer reset at the end of the round & timer reset when the player is taunting manually.

- Auto taunt is activated for hunters ( I think Hunters don't need to taunt ) and they get the same taunts as props.

**Comment by lucas2107** [comment]
I've found the problem.

When you go from Props to Hunters, the timer stay and you're taunting in Hunter.

**Comment by lucas2107** [comment]
#34

**Comment by daunknownman2010** [comment]
The AutoTaunt issues **should** be fixed in the _14j-staging_ branch. If there are further issues with AutoTaunt, please post below.

**Comment by blackjackph** [comment]
@daunknownman2010 could you tell me how to disable auto taunting? I've tried editing several files but nothing is working. I know this probably isn't the place to ask but I've tried asking in other places with no help.
P.S. This is what I've tried editing so far
This is what I've tried so far:
Edited the file in gamemodes/prop_hunt/gamemode/cl_autotaunt.lua
Edited the file in gamemodes/prop_hunt/gamemode/sh_init.lua 
Didn't think this would really help but I edited ""ph_autotaunt_enabled"" to ""ph_autotaunt_disabled" in gamemodes/prop_hunt/prop_hunt.txt
Got rid of "include("cl_autotaunt.lua")" in gamemodes/prop_hunt/gamemode/cl_init.lua
Got rid of "AddCSLuaFile("cl_autotaunt.lua")" in gamemodes/prop_hunt/gamemode/init.lua

**Comment by daunknownman2010** [comment]
@blackjackph Make sure you're using _14j-staging_ and set **ph_autotaunt_enabled** to 0 before the game starts. If this does not work, there is something causing the functions to not work properly. I don't have problems with the console variable right now.
