### ISSUE TITLE
Cannot toggle prop rotation

### ISSUE THREAD

**Issue by Puffin05** [Vinzuerio/ph-enhanced#36]
I have a little problem with the prop rotation lock.
I am not able to toggle prop rotation by pressing the R key.

**Comment by Vinzuerio** [comment]
Were you playing on server or hosting a server?

**Comment by Puffin05** [comment]
I invited a friend to my game on a 2 player server.

10 aug. 2017 kl. 05:47 skrev Wolvindra-Vinzuerio <notifications@github.com<mailto:notifications@github.com>>:


Were you playing on server or hosting a server?

**Comment by Vinzuerio** [comment]
make sure you've changed the 'ph_better_prop_movement' ConVar to 1 or use via Admin tab from Prop Hunt Menu.

If you already used that but nothing change, please explain why & when the rotation lock wont toggled

**Comment by Puffin05** [comment]
alright, ill try that
11 aug. 2017 kl. 18:56 skrev Wolvindra-Vinzuerio <notifications@github.com<mailto:notifications@github.com>>:


make sure you've changed the 'ph_better_prop_movement' ConVar to 1 or use via Admin tab from Prop Hunt Menu.

If you already used that but nothing change, please explain why & when the rotation lock wont toggled

**Comment by Puffin05** [comment]
I have now tried that, and the rotation lock simply wont toggle when i press the R key.

Skickat från min iPhone

11 aug. 2017 kl. 18:57 skrev Wolvindra-Vinzuerio <notifications@github.com<mailto:notifications@github.com>>:


make sure you've changed the 'ph_better_prop_movement' ConVar to 1 or use via Admin tab from Prop Hunt Menu.

If you already used that but nothing change, please explain why & when the rotation lock wont toggled

**Comment by Vinzuerio** [comment]
Is there any console error appears on server side?
and, Have you installed with latest build of PH:E from github (14j, workshop is: 14h)

**Comment by Puffin05** [comment]
There are no console errors, i got the Prop Hunt: Enhanced Addon from the Steam Workshop (http://steamcommunity.com/sharedfiles/filedetails/?id=417565863)

12 aug. 2017 kl. 17:29 skrev Wolvindra-Vinzuerio <notifications@github.com<mailto:notifications@github.com>>:


Is there any console error appears on server side?
and, Have you installed with latest build of PH:E from github (14j, workshop is: 14h)

**Comment by Vinzuerio** [comment]
Try use from github version, unsusbcribe from workshop version and classic prop hunt version.

**Comment by Puffin05** [comment]
Ok, ill try that

Skickat från min iPhone

18 aug. 2017 kl. 05:57 skrev Wolvindra-Vinzuerio <notifications@github.com<mailto:notifications@github.com>>:


Try use from github version, unsusbcribe from workshop version and classic prop hunt version.

**Comment by Vinzuerio** [comment]
I'll reopen this issue if this are still persists.
