### ISSUE TITLE
Player Names not working

### ISSUE THREAD

**Issue by Rhopper85** [Vinzuerio/ph-enhanced#37]
Can't seem to get player names to show up, which makes prop hunt near impossible. Any fix for this? I have "allow player names" enabled and it's still not working.

**Comment by Vinzuerio** [comment]
Listen server or dedicated server?

And have you re-downloaded all everything from the Github release? (or try with different commit versions before 14j)

For some reason, it both works listen & dedicated server, this may some missed configuration within your PH:E files that being replaced or conflicted.

This similar to happens that someone using modified (replaced) version of PH:E which the code isn't updated.

**Comment by daunknownman2010** [comment]
Normal TargetIDs will not appear for players on the opposite team to prevent people finding props easily with the HUD being painted. However, if you want to easily see where other players on your team are globally, use the _14j-staging_ branch and enable **ph_enable_plnames** for that very feature.
