### ISSUE TITLE
Can't enable autotaunt

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#40]
Hi,

ph_autotaunt_enabled	1 in config
AutoTaunt is not launching at the beginning of the round.

Best regards,

**Comment by daunknownman2010** [comment]
I could not replicate the issue as the convar works as expected on my side. Is there any additional information that could be shared to help us look into it (e.g. addons or gamemode version)?

**Comment by lucas2107** [comment]
The convar is not working for me, I tried on my dev server without anything else and it's working.
I'm going to check what's wrong with my addons.
