### ISSUE TITLE
ph_min_waitforplayers broken

### ISSUE THREAD

**Issue by Distortions81** [Vinzuerio/ph-enhanced#41]
I have to set ph_min_waitforplayers and ph_waitforplayers to 0, or rounds are broken and never start.

It would be great if there was a round-end cooldown, and first-round warmup ( to let people finish loading/connecting to a new map and join ).

Im hoping development isn't dead, so I dont have to rip out this code and start over.

**Comment by daunknownman2010** [comment]
Have you made sure you aren't using any other addons on your server? The system works as expected on my end.

**Comment by Distortions81** [comment]
Ill check things again, but i ended up adding a delay between rounds to let people connect, switch teams, and so on.

**Comment by Vinzuerio** [comment]
I'll Reopen this issue if the problem persists. Seems working on 14j staging branch
