### ISSUE TITLE
How to remove custom taunts message.

### ISSUE THREAD

**Issue by RainbowHG** [Vinzuerio/ph-enhanced#42]
Hi.

I'm using my own custom taunt menu that I want, however 
It seems I can't remove that darn "This server has custom taunts disabled" message.

I've even removed the code in the cl_tauntmenu Lua and search in every single Lua file for any more notifys or "disabled" chat message but can't see any.

The gamemode works great apart from this darn message.

**Comment by Vinzuerio** [comment]
https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/prop_hunt/gamemode/cl_tauntwindow.lua#L14

it usually follows from `CUSTOM_TAUNT_ENABLED` constant bool check. To prevent that message keeps appearing, simply remove from line 14 to 16
