### ISSUE TITLE
Camera for Props Glitching?

### ISSUE THREAD

**Issue by blackjackph** [Vinzuerio/ph-enhanced#44]
Whenever I am a prop and I look up, the camera gets switched so that it is like the camera is coming from the prop's point of view (like we are seeing stuff the way the prop would)
I thought it was my thirdperson camera addon but I disabled and deleted the addon and the problem still persists. 
If this is already an issue that has been fixed, I apologize but I did not see it on the list of closed issues so hopefully, it hasn't already been answered.
Thanks!

**Comment by blackjackph** [comment]
Nevermind, I simply had to turn off prop camera collisions. For anyone having the same issue, just put this in your server's config file:
ph_prop_camera_collision "0"

**Comment by Vinzuerio** [comment]
The 14j versions seems to fixed this issue. Try on D4 stage btw
