### ISSUE TITLE
Custom taunts

### ISSUE THREAD

**Issue by Falkio** [Vinzuerio/ph-enhanced#46]
Hello,
When i create a folder named taunts_custom that does not work
How to simply add custom taunts

**Comment by Vinzuerio** [comment]
Any console errors with `ph_print_verbose` enabled?
also, do you made the folders correctly within "sound/taunts/props_custom/" ?

if it's so, you might have to restart the server

**Comment by Falkio** [comment]
The gamemode will automaticaly detect the sounds?
Anything else To do?
No ERROR in console i think

**Comment by Falkio** [comment]
And what is the utility of serverlistener.cfg

**Comment by Vinzuerio** [comment]
serverlistener.cfg is used for when you're hosting a listen server. That file will be executed at every you launch a multiplayer session.

Also, the gamemode will automatically detect the sounds and adds the file into `resource.AddFile`, if you think you set it already, make sure `ph_enable_custom_taunts` is set to 1 or 2.

Make sure you also provide a FastDL to make sure it's downloads properly

**Comment by Vinzuerio** [comment]
custom sounds are now reworked. It should have to be fully working on v15 update release.
