### ISSUE TITLE
Lower the Damage of Guns?

### ISSUE THREAD

**Issue by blackjackph** [Vinzuerio/ph-enhanced#47]
Guns do way too much damage (like the magnum can kill an old man in one shot O.O)
How do I go about lowering this? I
I've searched the files but maybe I am using the wrong terms.

**Comment by blackjackph** [comment]
Okay, so I'm pretty sure I found out how to alter the damage. However, I can't find out which folders belong to the four main guns. 
In-game, the guns are the SMG, shotgun, etc but what are their folders labeled because I can't find them.
Thanks!

**Comment by Vinzuerio** [comment]
Those are Generic weapons that provided (originally) from Half-Life 2. The damage are controled by game engines by using several "sk_plr_dmg_*" ConVars.

**Comment by blackjackph** [comment]
Would you mind telling me which convars I would use to edit the damage of the main guns, then, because I can't find any documentation on how to

**Comment by daunknownman2010** [comment]
HL2's C++ weapons are controlled by "skill" console variables and is used to set the difficulty of the game. Wolvin's response gives you a start to using those **sk_** commands.

**Comment by blackjackph** [comment]
Yeah, Vinzuerio said that I had to use sk_plr_dmg Convars but by chance do you know what exact code I would use and where?

**Comment by Vinzuerio** [comment]
The weapon damages are stored and controlled by HL2's C++ "skill". It may depends by configuration of how much damage and skill level you have. however you can override it.

It simply can be found over your console. Just simply type "find sk_plr_dmg_" and it will be listed like this.

![image](https://user-images.githubusercontent.com/11814682/34903088-73caa146-f85c-11e7-9e97-3d1a1e8bd6ee.png)

note, several weapons may have no damage scaling at all, and it (may) reset over server or game restart, so you have to put them into your config file.
