### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Kapselll** [Vinzuerio/ph-enhanced#48]
How to add custom game models? (Dedicated server)

**Comment by Kapselll** [comment]
"Found unused .gma addon: golec_brothers_playermodels_1246022789.gma" I just put in in the addons and it didn't work.

**Comment by Kapselll** [comment]
Can someone help?

**Comment by Vinzuerio** [comment]
You simply put it but you don't subscribe it.

I'll reopen this issue if problem are still persists and relate to the gamemode, not personal addons problem

**Comment by Kapselll** [comment]
I did "menu_cleanupgmas" to fix the error message but the model isn't in the Model Chooser menu.

**Comment by daunknownman2010** [comment]
What "Model Chooser" are you using? Does this "Model Chooser" comply with Garry's Mod player_manager standards? Please be careful how you report issues, they must be detailed so people know what to look for.
