### ISSUE TITLE
Custom Taunts

### ISSUE THREAD

**Issue by Kapselll** [Vinzuerio/ph-enhanced#49]
I'm trying to add custom taunts. I wrote the paths etc.. Ingame I get this error:

HTTP ERROR 8 downloading http://(myfastdl)/s7214/sound/taunts/props_extra/ext_lulz.wav

There is an option to play the taunt in menu but when i try to play it in console this error pops out:

Failed to load sound "taunts\props_extra\ext_lulz.wav", file probably missing from disk/repository

**Comment by Vinzuerio** [comment]
Use the 14j staging branch here
https://github.com/Vinzuerio/ph-enhanced/tree/14j-staging

Just simply put your sounds pack into custom sound folder in "sound/taunts/hunters_custom/" for hunters and "sound/taunts/props_custom/" for props. Then the gamemode will add the download automatically. Don't forget to provide your sounds that able to be downloaded via FastDL and enabled with sv_downloadurl <url path>. This should prevent any download errors related with HTTP ERROR 8

**Comment by Kapselll** [comment]
I don't have these folders. In sounds/taunts/ i have "fixed", "hunters", "props" and "props_extra". Also they're not provided in ph_enhanced file (for dedicated servers edition) so i'm assuming that it should create when installing gamemode, but it didn't. Any ideas?

**Comment by daunknownman2010** [comment]
You have to create the folders yourself.

**Comment by Kapselll** [comment]
I fixed it, thanks
