### ISSUE TITLE
Scoreboard "Label"

### ISSUE THREAD

**Issue by aznninja5996** [Vinzuerio/ph-enhanced#50]
So I'm having this issue with the scoreboard. "Label" blocks are appearing underneath the column identifier and I can't seem to figure out what is causing this or how to fix it. I initially ran into this issue when running a server, so I decided to isolate the game mode. I have gone to the lengths of fully reinstalling the game while only adding this game mode and the ULX/ULIB addon via the Steam Workshop. I run this in single player and multiplayer and find myself with the same problem. Attached is a screenshot of my issue.

[https://ibb.co/fkfNgb](url)

**Comment by Vinzuerio** [comment]
Apparently several Fretta's VGUI elements are broken after December 2017 update. going to fix that or probably will replaced with new scoreboard

**Comment by aznninja5996** [comment]
Ah, of course, thank you for looking into it!

**Comment by Vinzuerio** [comment]
Update, this may seems caused by #52

**Comment by dhantasmic** [comment]
Think this can be closed now since #52 is solved.
