### ISSUE TITLE
Props are Not Banning?

### ISSUE THREAD

**Issue by squishybeans** [Vinzuerio/ph-enhanced#53]
I'm trying to ban a few props on my prop hunt server. I found out you can go into Sandbox mode, look up the prop, and right-click the model to get the model file location. For example, looking up the hula girl will give you this:

**models/props_lab/huladoll.mdl**

However, whenever I add it to the sh_config.lua file on my server it doesn't work. 

**Here is my sh_config.lua file:**

PHE.BANNED_PROP_MODELS = {

	"models/props/cs_assault/dollar.mdl",

	"models/props/cs_assault/money.mdl",

	"models/props/cs_office/snowman_arm.mdl",

	"models/props/cs_office/computer_mouse.mdl",

	"models/props/cs_office/projector_remote.mdl",

	"models/props/cs_militia/reload_bullet_tray.mdl",

	"models/props_lab/huladoll.mdl",

	"models/weapons/w_knife_ct.mdl",

	"models/weapons/w_knife_t.mdl",

	"models/weapons/cstrike/c_knife_t.mdl",

	"models/props_lab/clipboard.mdl",

	"models/foodnhouseholditems/egg.mdl"

}

The following are NOT working (they are not banned):

	"models/props_lab/huladoll.mdl",

	"models/weapons/w_knife_ct.mdl",

	"models/weapons/w_knife_t.mdl",

	"models/weapons/cstrike/c_knife_t.mdl",

	"models/props_lab/clipboard.mdl",

The other props listed do work but only because they came pre-banned. Am I typing the prop file path wrong?

**Comment by squishybeans** [comment]
Is there any solution to this? The problem still persists :(

**Comment by Jonpopnycorn** [comment]
I added **models/props_lab/huladoll.mdl** to the list and it worked just fine.
```
PHE.BANNED_PROP_MODELS = {
	"models/props/cs_assault/dollar.mdl",
	"models/props/cs_assault/money.mdl",
	"models/props/cs_office/snowman_arm.mdl",
	"models/props/cs_office/computer_mouse.mdl",
	"models/props/cs_office/projector_remote.mdl",
	"models/props/cs_militia/reload_bullet_tray.mdl",
	"models/props_lab/huladoll.mdl",
	"models/foodnhouseholditems/egg.mdl"
}
```

**Comment by squishybeans** [comment]
I don't understand why it's not working for me. I even tried deleting the sh_config.lua file and copying the exact file from the Wolvin's Github (I've had it where, when I downloaded the Enhanced Prop Hunt, for some reason, certain files were incomplete or corrupted.)
Is there another way to ban props because this option isn't working :(

**Comment by Jonpopnycorn** [comment]
This one?
https://github.com/Vinzuerio/ph-enhanced/archive/master.zip

Did you modify any other files than sh_config.lua

Do you have your cfg/server.cfg properly set? (http://project.wolvindra.net/phe_faq/#game_mapvote)
Make sure **ph_prop_collision** is set to **1**

Are you getting any lua errors? (if so which ones)

Also do you have any addons added? (if so which ones)
Try to remove all addons  except ulx/ulib and install each addon 1 at a time while testing the server to see if that addon affects it.

If you want you can add me on steam and I can probably help you out faster, instead of waiting for a response.

**Comment by squishybeans** [comment]
Yes, that's the file that I downloaded.
I've modified other files, but mostly stuff like turning off autotaunts, allowing all players to talk (sv_alltalk "3") ph_prop_camera_collisions "0", stuff like that.

I'll try to set the prop collision to one right now.

I have lua errors, like missing VGUI materials on certain maps but nothing other than that.
 As for addons, I have pointshop player models (do you want me to list those?), I have a double jump addon (that's lets players, obviously double jump lol), a scoreboard skin, and a pointshop skin.
But would any of those even effect that?

**Comment by squishybeans** [comment]
It works! :D I found out that I was editing the wrong sh_config.lua file. The file I had been editing was here:
garrysmod/gamemodes/prop_hunt/gamemode/sh_config.lua

But I should have been editing:
garrysmod/addon/ph-enhanced-master/gamemodea/prop_hunt/gamemode/sh_config.lua

I didn't realize there was another sh_config.lua file lol 
But thank you so much for your help! I wouldn't have even know about that file had you not pasted that URL :D
