### ISSUE TITLE
Team Numbers?

### ISSUE THREAD

**Issue by TheHeroBilly** [Vinzuerio/ph-enhanced#54]
I've got a custom score board but the teams always stack under one side, I need the Team Numbers so they stack properly, and I can't seem to find them anywhere.

I need 4 numbers

Hunters 
Props
Spec
Unassigned

thanks

**Comment by Jonpopnycorn** [comment]
Hunters = 1 or TEAM_HUNTERS
Props = 2 or TEAM_PROPS
Spectator = 1002 or TEAM_SPECTATOR
Unassigned = 1001 or TEAM_UNASSIGNED
