### ISSUE TITLE
Maps Not Being Excluded from Votelist

### ISSUE THREAD

**Issue by squishybeans** [Vinzuerio/ph-enhanced#56]
Hello, I'm trying to exclude certain maps from the votelist but it's not working.
Here are the steps I followed:
Typed !menu
Went to Settings > ULX Player Votemap List
Removed desired maps.

However, the maps are still included in the votelist. Do I need to edit the files or is this a bug? 
Thanks for your help!

**Comment by Vinzuerio** [comment]
ULX map votemap list isn't similar as the mapvote does. use `mv_mapprefix` convar to split which maps that should be listed in to the mapvote.

https://project.wolvindra.net/phe_faq/#game_ConVar_mapvote

**Comment by Vinzuerio** [comment]
I've made some changes related to this issue.
The Next update of V15 is now alow you to whitelist several ULX Maps and you can list your map into MapVote by using a ConVar: `mv_use_ulx_votemaps 1`

Be sure to always have your ULX installed.
