### ISSUE TITLE
New hud on 1.15 broken

### ISSUE THREAD

**Issue by gillie44** [Vinzuerio/ph-enhanced#59]
On first launch with new version, the hud is full of missing textures (purple and black squares). After a game restart the normal hud is not drawn at all and the following error is repeated in the console: 
Error in hook HUDShouldDraw: gamemodes/prop_hunt/gamemode/cl_hud.lua:42: attempt to index a nil value
stack traceback:
gamemodes/prop_hunt/gamemode/cl_hud.lua:42: in function 'fn'

**Comment by gillie44** [comment]
After a server restart the hud was fixed. Might just be that the gamemode needs a second restart for the new_hud convar to be created

**Comment by Vinzuerio** [comment]
Yeah the ConVars if you updated directly while gamemode is running wont take effect, unless you take a full gmod server restart to apply it.

**Comment by Vinzuerio** [comment]
Also closing this issue since this has no problem. If anything, re-open the issue if there's another problem related to this.
