### ISSUE TITLE
voice chat symbol shown on props

### ISSUE THREAD

**Issue by darkyyyy** [Vinzuerio/ph-enhanced#6]

**Comment by Jonpopnycorn** [comment]
@darkyyyy When the AllTalk setting is set to Team, then the only ones that can see the voice chat symbol or hear them are team members, but if you have it set to everyone then anyone can see the voice chat symbol and hear that person.

**Comment by Vinzuerio** [comment]
you can use "mp_show voice icons" set into 0.
