### ISSUE TITLE
Convars not detected

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#60]
Unknown command "ph_use_playermodeltype"
Unknown command "ph_prop_jumppower"
Unknown command "ph_notice_prop_rotation"
Unknown command "ph_fc_use_single_sound"
Unknown command "ph_fc_cue_path"
Unknown command "mv_allowcurmap"
Unknown command "mv_cooldown"
Unknown command "mv_mapbeforerevote"
Unknown command "mv_maplimit"
Unknown command "mv_rtvcount"
Unknown command "mv_timelimit"
Unknown command "mv_use_ulx_votemaps"
Unknown command "mv_mapprefix"

All of them aren't detected.

**Comment by Vinzuerio** [comment]
Update your sv_convars, sh_mapvote, as well as votemaps/*

It seems several of your remaining files do not update properly.
