### ISSUE TITLE
Lucky ball Icon

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#64]
Lucky ball Icon is growing more and more when you're far from them.

**Comment by Vinzuerio** [comment]
it should be intended for it just to make sure it 'stays'. Not sure if someone could enhance the icon to stay with fixed size.

**Comment by Vinzuerio** [comment]
Think I fixed it. Expect on Revision B update patch. No more 'Sprite' painting but instead using `DrawTextureRect`

![20180516110516_1](https://user-images.githubusercontent.com/11814682/40096119-a11521f0-58f9-11e8-8a70-12428e5d422d.jpg)
![20180516110523_1](https://user-images.githubusercontent.com/11814682/40096120-a15a37b8-58f9-11e8-9fb7-71d90dc67536.jpg)
