### ISSUE TITLE
Waiting for start round and no 'Player joined the game' message

### ISSUE THREAD

**Issue by pawelxxdd** [Vinzuerio/ph-enhanced#65]
1. I downloaded latest version from GitHub for my server and round doesn't start. There is still "Waiting for start round" text in top of my screen. Even if there are 2 players on the server.
2. When someone joins the server, the console shows an error that does not display the information on the chat (ex. '<Player> joined the game')

**Comment by Vinzuerio** [comment]
Please post amy error console, we cannot investigate on what is actually causing that the gamemode is failed.

**Comment by Vinzuerio** [comment]
You seems forgot to update in the addons folder as well. `addons/ph-enhanced` ones are not updated properly and/or invalid. You probably putting some wrong taunts in the folder which is now requires named index value. like
```
["Taunt Name"] = "taunt/path.wav",
```
but instead
```
"taunt/path.wav",
"another/list.wav"
```

Reason two, you might probably using the taunt pack loader which is outdated. Remove if any.

**Comment by pawelxxdd** [comment]
Ok, I will install the latest version on my server and try to fix it. Thanks

**Comment by pawelxxdd** [comment]
OK. It works very fine. Very nice job man. Thanks ;) Have a nice day
