### ISSUE TITLE
Big Hitboxes for Props

### ISSUE THREAD

**Issue by anthonyntsc** [Vinzuerio/ph-enhanced#66]
I've updated to 15 recently on a server of mine and a lot of players and I have noticed that the hitboxes for Props have gotten significantly larger - Hunters don't have to be as precise and accurate to hit Props

Is there a way to get the older smaller hitboxes for Props?

**Comment by Vinzuerio** [comment]
Any error console happened?  Plus you might using addon playermodel which causes the hitbox are messed up.

**Comment by anthonyntsc** [comment]
It was answered in #51 
It was the result of using the fixed hitbox - I was using an outdated version of the gamemode before 14 before I updated
