### ISSUE TITLE
Server settings don't apply to all players

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#70]
Hi,

Since I updated to the latest version, some players who had an old version of PH:enhanced don't receive default server settings.

**Comment by Vinzuerio** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=417565863

_'Version 15 Revision C has been released. 
There might be no backward versions & revisions as it is will be no support anymore.'_ 

This may subject any older version that will remain unsupported. Including players that still using the old versions.

If the player is still using the old version, they **must** have to update the version to the latest one. This to prevent any missbehaviour happening during the gameplay such as the UI being messed up, network vars are not sending properly, and many others.

**Comment by lucas2107** [comment]
That doesn't make any sense.
I don't think you understand.

People who had an old version of prop hunt ( Revision 14 ) before the Revision 15 update are have this problem. People who didn't had Revision 14 installed before don't have this problem.

But they're receiving Revision 15 files from workshop when they connect to the server...

**Comment by Vinzuerio** [comment]
SomeConVars can be "archived" and "not archived", there are some convars as well that marked replicated and not.

Also, do you mean server settings is like it should be synchronized to the clients (after they disconnected) and then the settings will apply after they creating a new multiplayer game?

**Comment by lucas2107** [comment]
No, settings are differents on each servers. So, when someone play on a server convars should be the same client side and server side. Atm, client side convars differs from the server.
