### ISSUE TITLE
Can't Hear Custom Taunts

### ISSUE THREAD

**Issue by cookieman768** [Vinzuerio/ph-enhanced#71]
I placed the custom taunt wav file in garrysmod/sound/taunts/props_custom as per the wiki but it doesn't appear in the taunt menu.

**Comment by cookieman768** [comment]
I managed to fix this by using Fast DL. I wish the wiki would suggest using fast DL though.

**Comment by Vinzuerio** [comment]
updated wiki, also however for the fastdl code section in `sh_config.lua` for auto-taunts is also being fixed. it should be available now for client to be downloaded.
