### ISSUE TITLE
sh_phe_additional_taunts.lua not added until 1st player joins

### ISSUE THREAD

**Issue by katawajojo** [Vinzuerio/ph-enhanced#73]
Upon the 1st player joining a server, the taunts in `sh_phe_additional_taunts.lua` are loaded and added to FastDL. The issue with this is that they're not being loaded at GM.Initialize, but GM.PostMapCleanup, meaning a player has already been served the FastDL list by this time, and the 1st connected user doesn't obtain said custom taunts from `sh_phe_additional_taunts.lua`

Additionally, switching 
```
hook.Add("PostCleanupMap","PHE.RefreshTaunts",function()
	PHE:RefreshTauntList()
end)
```

to 

```
hook.Add("Initialize","PHE.RefreshTaunts",function()
	PHE:RefreshTauntList()
end)
```

results in:

```
[ERROR] lua/includes/extensions/table.lua:50: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Empty - lua/includes/extensions/table.lua:50
    3. RefreshTauntList - gamemodes/prop_hunt/gamemode/sh_config.lua:315
     4. fn - gamemodes/prop_hunt/gamemode/sh_config.lua:345
      5. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
```

(assuming because sh_phe_additional_taunts.lua isn't being loaded until later on?)

Obvious workaround: launch server, connect to server, disconnect.

**Comment by Vinzuerio** [comment]
Thats why it user timer, rather than using the initialize. For some reason, i have to avoid initialize because the taunt maybnot be recognised due to addon sorting & loading time, which this can't be prevented

**Comment by Vinzuerio** [comment]
Another note mentioning about the server starting the events even after 1st player joins, this is unknown if thid caused by the fretta itself or what hook causef this has to be 'waited'

**Comment by daunknownfox2010** [comment]
Should be working properly in **v15-g**. If it isn't please let me know.
https://github.com/Vinzuerio/ph-enhanced/tree/v15-g
