### ISSUE TITLE
Pointshop 2 Integration

### ISSUE THREAD

**Issue by alkapote** [Vinzuerio/ph-enhanced#77]
Hello everyone.
I have some issues on my PH:E server:

My players doesn't earn any points at the end of a round.
I follow this tutorial for PH:E :  

https://steamcommunity.com/workshop/filedetails/discussion/417565863/135511259335552096/

But it's talking about an old version
Could you help me please?

Regards

**Comment by daunknownfox2010** [comment]
As a reminder: Pointshop 2 is not officially supported by us as it's a paid addon. There is apparently a PH:E integration for PS2 floating around, however, you must pay for it unfortunately.

Closing as it's not an issue with the gamemode, it's something the PS2 community will need to work on.
