### ISSUE TITLE
Issue with admin menu on version g eos

### ISSUE THREAD

**Issue by NubileEye** [Vinzuerio/ph-enhanced#78]
I recently created a server, and added my workshop and addons, as well as tried to use the latest version of this mode, revision G.

However, I got the following error in console upon trying to open the prop hunt menu tab after pressing F1.

[ERROR] gamemodes/prop_hunt/gamemode/cl_menu.lua:59: attempt to index a nil value
  1. CreateVGUIType - gamemodes/prop_hunt/gamemode/cl_menu.lua:59
   2. ShowAdminMenu - gamemodes/prop_hunt/gamemode/cl_menu.lua:535
    3. func - gamemodes/prop_hunt/gamemode/cl_menu.lua:645
     4. unknown - lua/includes/extensions/net.lua:32

I believe this is related to being opped as an admin as when I open it as a regular user, no such error occurs. Unfortunately this is quite a breaking bug imho as I like to adjust some settings on the admin tab. Is there any way to fix this?

I get this bug consistently, no matter if I download the workshop version, the version from github, or etc. I currently am trying to host this gamemode on a dedicated server, but it appears locally as well.

Any help?

**Comment by Storm1** [comment]
I am having the exact same problem as an admin. Players don't get the script errors.

**Comment by MayhemBill** [comment]
It's trying to spawn the admin menu, it does the same for me. Not sure why as I don't know lua well enough to fix it.

**Comment by Vinzuerio** [comment]
Should be fixed on next Revision H.

Sorry about that, I forgot to remove a cvar check for Taunt Scanner Directory
