### ISSUE TITLE
[Help]Table for points while taunting (Pointshop)

### ISSUE THREAD

**Issue by Darkouille81** [Vinzuerio/ph-enhanced#8]
Hello here, i've made the upload of the gamemode, i take the default init config and added this line code :
`function GM:ShowSpare1(pl)
	if GAMEMODE:InRound() && pl:Alive() && (pl:Team() == TEAM_HUNTERS || pl:Team() == TEAM_PROPS) && pl.last_taunt_time + TAUNT_DELAY <= CurTime() && #PROP_TAUNTS > 1 && #HUNTER_TAUNTS > 1 then
		repeat
			if pl:Team() == TEAM_HUNTERS then
				rand_taunt = table.Random(HUNTER_TAUNTS)
			else
				rand_taunt = table.Random(PROP_TAUNTS)
			end
		until rand_taunt != pl.last_taunt
		
		pl.last_taunt_time = CurTime() + rand_taunt[2]
		pl.last_taunt = rand_taunt
		
		pl:EmitSound(rand_taunt[1], 100)
		if pl:Team() == TEAM_PROPS then
			pl:PS_GivePoints(rand_taunt[2])
			pl:PS_Notify("Vous avez gagné ",rand_taunt[2]," ", PS.Config.PointsName, " pour avoir taunté !")
		end
	end	
end`

Aswell i've added the table in the sh_config : (example for hunter) I KNOW IN HUNTER IT DIDN'T GIVE POINTS, i've made the same for props.
`HUNTER_TAUNTS = {

	-- Normal Taunts
	{"taunts/hunters/come_to_papa.wav",1},
	{"taunts/hunters/father.mp3",2},
	{"taunts/hunters/fireassis.wav",2},
	{"taunts/hunters/hitassist.wav",1},
	{"taunts/hunters/now_what.wav",1},
	{"taunts/hunters/you_dont_know_the_power.wav",4},
	{"taunts/hunters/you_underestimate_the_power.wav",3},
	{"taunts/hunters/glados-president.wav",4},
	{"taunts/hunters/rude.mp3",1},
	{"taunts/hunters/soul.mp3",4},
	{"taunts/hunters/illfindyou.mp3",6},
	{"taunts/hunters/philipejesais.mp3",10},
	{"taunts/hunters/hunter1.mp3",3},
	{"taunts/hunters/hunter5.mp3",12},
	{"taunts/hunters/ih0008a.mp3",3},
	{"taunts/hunters/maisouicestclair.mp3",1},
	{"taunts/hunters/starwars.mp3",9},
	{"taunts/hunters/pgm.mp3",34},
	{"taunts/hunters/ilestlailestla.mp3",1},
	
	--Deus Ex
	{"taunts/props_extra/dx_augmented.wav",2}

}`

This was working on old version, now taunts are glitchy, no points win, none of added taunts are played.
And in the custom taunt list i have : 
table######## <----- Letters and numbers
and the others taunts from prop_taunts.lua

I will keep an eye on this post, there is my steam :
http://steamcommunity.com/profiles/76561198087405083/
If i found a way to correct it, i will post how to.
If you want more info, ask !

**Comment by Jonpopnycorn** [comment]
@Darkouille81 What error(s) does are you getting?

**Comment by Darkouille81** [comment]
In the server console, nothing
In the game console nothing when i join and when i taunt

**Comment by Vinzuerio** [comment]
You've forgotten some few things on there :

`until rand_taunt != pl.last_taunt` should be `until rand_taunt[1] != pl.last_taunt`
`pl.last_taunt = rand_taunt` should be `pl.last_taunt = rand_taunt[1]`

See if it works.

**Comment by Vinzuerio** [comment]
Here's the working code.
`function GM:ShowSpare1(pl)
	if GAMEMODE:InRound() && pl:Alive() && (pl:Team() == TEAM_HUNTERS || pl:Team() == TEAM_PROPS) && pl.last_taunt_time + TAUNT_DELAY <= CurTime() && #PROP_TAUNTS > 1 && #HUNTER_TAUNTS > 1 then
		repeat
			if pl:Team() == TEAM_HUNTERS then
				rand_taunt = table.Random(HUNTER_TAUNTS)
			else
				rand_taunt = table.Random(PROP_TAUNTS)
			end
		until rand_taunt[1] != pl.last_taunt
		
		pl.last_taunt_time = CurTime() + rand_taunt[2] -- Did you meant to add extra time for it?
		pl.last_taunt = rand_taunt[1]
		
		pl:EmitSound(rand_taunt[1], 100)
		if pl:Team() == TEAM_PROPS then
			pl:PS_GivePoints(rand_taunt[2])
			pl:PS_Notify("Vous avez gagné ",rand_taunt[2]," ", PS.Config.PointsName, " pour avoir taunté !")
		-- else for hunter here.
		end
	end	
end`

Works on my side, in debug mode.
![works1](https://cloud.githubusercontent.com/assets/11814682/20044763/229bf352-a4ce-11e6-9c20-188ecb1d6489.jpg)

**Comment by Darkouille81** [comment]
I'm trying in a few minutes and say if it works =)
Thanks for this help mate.
