### ISSUE TITLE
Change map when i leave my server

### ISSUE THREAD

**Issue by gamenumi** [Vinzuerio/ph-enhanced#82]
Hello, first of all, excuse me for my english,

I have a pretty annoying problem.
when I leave my server garry's mod prop hunt, the server changes the map all by itself and decides by itself to choose a map that I did not configure. for example: de_dust.

Do you know of any problem?

Thank you for your future answer

**Comment by Vinzuerio** [comment]
This is the fretta doing it's job. Causes if there is no player, it will automatically finishes the round and will change to other maps, but unless if the first round's timer is exhausted.

I'm currently trying to workaround of this to make sure it does not even change to other map once the player leave or the timer ends.

**Comment by Vinzuerio** [comment]
Got the problem, MapVote will call the MapVote.Start after player disconnect. Going to add a cvar that should prevent this executing if there is no player.

Expect the fix for the new update very soon

**Comment by gamenumi** [comment]
Wow, thanks for your quick reply.

You are doing a very good job. Good day to you.

**Comment by Vinzuerio** [comment]
No problem!
