### ISSUE TITLE
CL2SV_PlayThisTaunt in cl_tauntwindow

### ISSUE THREAD

**Issue by lucas2107** [Vinzuerio/ph-enhanced#83]
CL2SV_PlayThisTaunt was disabled but still used for Custom taunts at line 202 in cl_tauntwindow

**Comment by Vinzuerio** [comment]
Functions are moved to here
https://github.com/Vinzuerio/ph-enhanced/blob/master/gamemodes/prop_hunt/gamemode/sv_autotaunt.lua

Sorry, this for safety purpose.
