### ISSUE TITLE
Replace MapVote System

### ISSUE THREAD

**Issue by Chillstice** [Vinzuerio/ph-enhanced#85]
I have access to [Clean Map Vote](https://www.gmodstore.com/market/view/clean-map-vote-the-simplistic-map-voting-system) which is an alternative map-vote system.

I would like to replace the default map-vote system built into PHE with this instead. 

Clean Map Vote registers a console command and ulx menu commands to initiate the map-vote menu. 
I'm looking to replace the function that generated the PHE map vote menu with a function that just runs the console command to open Clean Map Vote, but I don't know which file/ where to do that. 

Could I get some assistance? Maybe it would be good to include instructions on how to do this in the wiki as well.

**Comment by Vinzuerio** [comment]
You can simply change the default `MapVote.Start()` in fretta code into your Clean Map Vote's call, or simply comments them if you want to override from your Clean Map Vote's hook call (if any)

Source: https://github.com/Vinzuerio/ph-enhanced/blob/b71e9cce8af306a88b53c5ce5df0b0c91d72e363/gamemodes/fretta/gamemode/init.lua#L512

This method already mentioned in https://prophunt.wolvindra.net/faq/?dir=Faq&gettopic=Gamemode_FAQ , guess Might have to write again to a new wiki platform instead.

**Comment by Vinzuerio** [comment]
added to Revise-Addition list: Replacable MapVote System on V16 by using a hook.

**Comment by Chillstice** [comment]
Thanks, I haven't done any rigorous testing, but I think this is the solution.

In my case the function is called `CMV:Start()`
