### ISSUE TITLE
[PH: Enhanced - Taunt] Warning: This server has custom taunts disabled.

### ISSUE THREAD

**Issue by Vickramvijay** [Vinzuerio/ph-enhanced#9]
Although the ph_enable_custom_taunts is set to 1, and I've set up custom taunts in my taunts\custom_taunts folder it still gives me the error. Any idea whats up?

**Comment by Vinzuerio** [comment]
There's nothing wrong with the code, tested on live server.
Maybe it caused by your config (server.cfg) that overrides the "ph_enable_custom_taunts" to 0 ?

Also, make sure you didn't messed up with the sh_config of the taunts table. If you are not sure about the taunts, you can paste your custom taunt code list here.

**Comment by Vickramvijay** [comment]
Thanks for the really prompt reply!!!

Heres' my sh_config:
-- Global Var for custom taunt, delivering from taunts/prop -or- hunter_taunts.lua
PH_TAUNT_CUSTOM = {}
include("taunts/hunter_taunts.lua")
include("taunts/prop_taunts.lua")

-- \\ General Gamemode Config // --

-- Maximum time (in minutes) for this fretta gamemode (Default: 30)
GAME_TIME = GetConVarNumber("ph_game_time")
-- Number of seconds hunters are blinded/locked at the beginning of the map (Default: 30)
HUNTER_BLINDLOCK_TIME = GetConVarNumber("ph_hunter_blindlock_time")
-- Health points removed from hunters when they shoot  (Default: 25)
HUNTER_FIRE_PENALTY = GetConVarNumber("ph_hunter_fire_penalty")
-- How much health to give back to the Hunter after killing a prop (Default: 100)
HUNTER_KILL_BONUS = GetConVarNumber("ph_hunter_kill_bonus")
-- Seconds a player has to wait before they can taunt again (Default: 2 or 3)
TAUNT_DELAY = 0
-- Rounds played on a map (Default: 10)
ROUNDS_PER_MAP = GetConVarNumber("ph_rounds_per_map")
-- Time (in seconds) for each round (Default: 300)
ROUND_TIME = GetConVarNumber("ph_round_time")
-- Determains if players should be team swapped every round [0 = No, 1 = Yes] (Default: 1)
SWAP_TEAMS_EVERY_ROUND = GetConVarNumber("ph_swap_teams_every_round")
-- Time (in seconds) for props to play custom taunts again (Default: 6)
CUSTOM_TAUNT_DELAY = GetConVarNumber("ph_customtaunts_delay")

-- Banned Props models
--[[ Add one of your owns model restriction if you have problems. 
	these lists are usually common props that has been used on every maps. ]]--
BANNED_PROP_MODELS = {
	"models/props/cs_assault/dollar.mdl",
	"models/props/cs_assault/money.mdl",
	"models/props/cs_office/snowman_arm.mdl",
	"models/props/cs_office/computer_mouse.mdl",
	"models/props/cs_office/projector_remote.mdl",
	"models/props/cs_militia/reload_bullet_tray.mdl",
	"models/foodnhouseholditems/egg.mdl"
}

-- Additional Props Models instead of being Kleiner so... he will no longer lonely.
ADDITIONAL_STARTING_MODELS = {
	"models/player/kleiner.mdl",
	"models/player/alyx.mdl",
	"models/player/barney.mdl",
	"models/player/eli.mdl",
	"models/player/mossman.mdl",
	"models/player/breen.mdl"
}

--[[ // DO NOT MODIFY! use from taunts/prop_taunts.lua or hunter_taunts.lua instead! \\ ]]--
HUNTER_TAUNTS = {
	"taunts/hunters/come_to_papa.wav",
	"taunts/hunters/father.mp3",
	"taunts/hunters/fireassis.wav",
	"taunts/hunters/hitassist.wav",
	"taunts/hunters/now_what.wav",
	"taunts/hunters/you_dont_know_the_power.wav",
	"taunts/hunters/you_underestimate_the_power.wav",
	"taunts/hunters/glados-president.wav",
	"taunts/hunters/rude.mp3",
	"taunts/hunters/soul.mp3",
	"taunts/hunters/illfindyou.mp3",
	"vo/npc/male01/vanswer13.wav",
	"vo/npc/male01/thehacks01.wav",
	"vo/npc/male01/runforyourlife02.wav",
	"vo/npc/male01/overhere01.wav",
	"vo/npc/male01/overthere01.wav",
	"vo/npc/male01/overthere02.wav"
}

--[[ // DO NOT MODIFY! use from taunts/props_taunts.lua or hunters_taunts.lua instead! \\ ]]--
PROP_TAUNTS = {
	"taunts/boom_headshot.wav",
	"taunts/go_away_or_i_shall.wav",
	"taunts/ill_be_back.wav",
	"taunts/negative.wav",
	"taunts/doh.wav",
	"taunts/oh_yea_he_will_pay.wav",
	"taunts/ok_i_will_tell_you.wav",
	"taunts/please_come_again.wav",
	"taunts/threat_neutralized.wav",
	"taunts/what_is_wrong_with_you.wav",
	"taunts/woohoo.wav",
	"taunts/props/1.wav",
	"taunts/props/2.wav",
	"taunts/props/3.wav",
	"taunts/props/4.wav",
	"taunts/props/5.wav",
	"taunts/props/6.wav",
	"taunts/props/7.wav",
	"taunts/props/8.wav",
	"taunts/props/9.wav",
	"taunts/props/10.wav",
	"taunts/props/11.wav",
	"taunts/props/12.wav",
	"taunts/props/14.wav",
	"taunts/props/15.wav",
	"taunts/props/16.wav",
	"taunts/props/17.mp3",
	"taunts/props/18.wav",
	"taunts/props/19.wav",
	"taunts/props/20.wav",
	"taunts/props/21.wav",
	"taunts/props/22.wav",
	"taunts/props/23.wav",
	"taunts/props/24.wav",
	"taunts/props/25.wav",
	"taunts/props/26.wav",
	"taunts/props/27.wav",
	"taunts/props/28.wav",
	"taunts/props/30.wav",
	"taunts/props/31.mp3",
	"taunts/props/32.mp3",
	"taunts/props/33.mp3",
	"taunts/props/34.mp3",
	"taunts/props/35.mp3",
	"vo/citadel/br_ohshit.wav",
	"vo/citadel/br_youfool.wav",
	"vo/citadel/br_youneedme.wav",
	"vo/coast/odessa/male01/nlo_cheer01.wav",
	"vo/coast/odessa/male01/nlo_cheer02.wav",
	"vo/coast/odessa/male01/nlo_cheer03.wav",
	"vo/coast/odessa/male01/nlo_cheer04.wav",
	"vo/coast/odessa/female01/nlo_cheer01.wav",
	"vo/coast/odessa/female01/nlo_cheer02.wav",
	"vo/coast/odessa/female01/nlo_cheer03.wav",
	"vo/gman_misc/gman_riseshine.wav",
	"vo/npc/barney/ba_damnit.wav",
	"vo/npc/barney/ba_laugh01.wav",
	"vo/npc/barney/ba_laugh02.wav",
	"vo/npc/barney/ba_laugh03.wav",
	"vo/npc/barney/ba_laugh04.wav",
	"vo/npc/male01/hacks01.wav",
	"vo/npc/male01/hacks02.wav",
	"vo/npc/male01/vanswer01.wav",
	"vo/npc/male01/question05.wav",
	"vo/npc/male01/question06.wav",
	"vo/npc/male01/answer34.wav",
	"vo/npc/male01/question30.wav",
	"vo/npc/male01/question26.wav",
	"vo/npc/male01/incoming02.wav",
	"vo/npc/male01/gethellout.wav",
	"vo/ravenholm/madlaugh04.wav",
	"taunts/fixed/13_fix.wav",
	"taunts/fixed/bees_fix.wav",
	"taunts/hunters/laugh.wav"
}

-- Add custom taunts, if any. See taunts/prop_taunts.lua or taunts/hunter_taunts.lua for more info.
local function AddDemTaunt()
	print("[PH: Enhanced] Adding custom prop taunts...")
	if PH_TAUNT_CUSTOM.PROP != nil then
		for k,prop in pairs(PH_TAUNT_CUSTOM.PROP) do 
			table.insert(PROP_TAUNTS, prop)
		end
	else
		print("[PH: Enhanced] WARNING! Custom taunts table is EMPTY!!")
	end
	
	print("[PH: Enhanced] Adding custom hunter taunts...")
	if PH_TAUNT_CUSTOM.HUNTER != nil then
		for k,hunter in pairs(PH_TAUNT_CUSTOM.HUNTER) do 
			table.insert(HUNTER_TAUNTS, hunter)
		end
	else
		print("[PH: Enhanced] WARNING! Custom taunts table is EMPTY!!")
	end
end

AddDemTaunt()


and here's the prop_taunts.lua:

PH_TAUNT_CUSTOM.PROP = {
"taunts/custom_taunts/boom_headshot.wav",
"taunts/custom_taunts/doh.wav",
"taunts/custom_taunts/go_away_or_i_shall.wav",
"taunts/custom_taunts/my_taunts_x.ogg"
}

I still can't seem to find any reason and I haven't touched my server.cfg since installing the addon on my server so it can't be cuz its overridden, and when I type the ph_enable_custom_taunts in the console it replies that its = 1 although I'm having issues when I press 'c' in game

**Comment by Vinzuerio** [comment]
Were you trying in singleplayer? or Multiplayer on Listenserver, but not Dedicated server (from steamcmd?)

**Comment by Vickramvijay** [comment]
I'm playing on a dedicated server, I'll try again on a new fresh dedicated server with the following prerequisites(tell me if I missed anything):
1.ULX 
2.Four taunts to test in the taunts/custom_taunts folder
3. ONLY changing the prop_taunts.lua file to include my taunts and ONLY changing the sh_config from 0 to 1 for custom taunts

**Comment by Vickramvijay** [comment]
entirely different issue now, taunt menu works great but the custom taunts aren't being downloaded to the client so its unable to be played. Am I right that custom taunts should be in garrysmod\addons\Prop Hunt Enhanced V14d\sound\taunts\props_extra and that the command for it to be added in prop_taunts.lua should be "taunts/props_extra/balls_of_steel.mp3". It is showing up in the custom taunts panel but can't be played cuz the client doesnt seem to have downloaded it

**Comment by Vickramvijay** [comment]
So with regards to the prophunt taunt menu not working that was  a fault on my part but I still can't get clients to download the taunts. On a fresh new server all I did was make custom taunts = 1 so the taunt menu now works. In addition to the pre-given taunts I've added a John Cena taunt to the server by making only 2 changes:

The first change was adding it to the prop_taunts.lua:
PH_TAUNT_CUSTOM.PROP = {
	"taunts/props_extra/John.mp3",
	"taunts/props_extra/dx_idonotmoveout.wav",
	"taunts/props_extra/dx_iloominarty.wav",
	"taunts/props_extra/dx_imgonnawoopyourass.wav",
	"taunts/props_extra/dx_lookatme.wav",
	"taunts/props_extra/dx_molepeople.wav",
	"taunts/props_extra/dx_thebomb.wav",
	"taunts/props_extra/dx_thebomb2.wav",
	"taunts/props_extra/ext_angry_german_kid.wav",
	"taunts/props_extra/ext_blablaahah.wav",
	"taunts/props_extra/ext_dance_music.wav",
	"taunts/props_extra/ext_get_no_scope.wav",
	"taunts/props_extra/ext_hl1_crackmod_ihateyou.wav",
	"taunts/props_extra/ext_hl1_crackmod_watchyourrear.wav",
	"taunts/props_extra/ext_hl1_crackmod_youareugly.wav",
	"taunts/props_extra/ext_jojon_sina.wav",
	"taunts/props_extra/ext_just_do_it_1.wav",
	"taunts/props_extra/ext_just_do_it_2.wav",
	"taunts/props_extra/ext_woo.wav",
	"taunts/props_extra/ext_huladance.mp3",
	"taunts/props_extra/ext_wepon.mp3",
	"taunts/props_extra/ext_x_files.wav"
}

Secondly I added John.mp3 to the same folder as the rest, which is addons\Prop Hunt Enhanced V14d\sound\taunts\props_extra. 

But even after doing so clients do not download the taunts when connecting to my dedicated server and can see it in the taunt menu and use ALL other taunts except John.mp3

**Comment by Vinzuerio** [comment]
I'd like to make sure again that:
Firstly, this can be your addon folder naming that contains capital letter with space, which in linux (if you're hosting with) may not supported. You might have to use with small letters with underscore instead. However if you're on windows, you might have to do with similar way with this. That's why some of your taunts might not loaded properly, or this could be your coding typo.

Secondly, if you're facing issues that client can't listen to the taunts, you need to make them downloads by using `resource.AddFile("sound/your_sound_path/here.wav")`, following with all your custom sounds that you have provided. 
To do this, you might need to put in your custom lua file (by creating one in lua/autorun/server), otherwise put them in init.lua which must be located on top of the code. This will let the client will download your custom taunt sounds from the server.

You also need to specify your download URL by using convar sv_downloadurl "http://youraddress/fastdl/" and the path should contains similar to your content to addons folder must be exact. for example:
- (your web root)/fastdl/materials , which was on addons: /garrysmod/addons/ph_enhanced_v14/materials/
- (web root)/fastdl/sound, addons: /garrysmod/addons/ph_enhanced_v14/sound/
- and etc...

Then add these command and point to your address/IP inside your server.cfg:
`sv_downloadurl "http://192.x.x.x/fastdl".`

I've been tested in all way and this could be the related problem, hope this could fix the issue.

**Comment by Vickramvijay** [comment]
Omg thanks soooo much! You managed to fix my problem, I was being an idiot and totally forgot to include the new custom sounds in my ftp server cuz I didn't realise the filesystem changed when I upgraded from the old version to your dank enhanced one, to those who still have issues make sure you include the custom sound files in both garrysmod/sound and within your addons folder as well. Also thanks so much and I really respect what you're doing here helping the community so I'd like to offer you a token of gratitude through steam as I'm currently a student and I cannot donate to your paypal. If you're interested please add me at www.steamcommunity.com/id/yomamaisagay thanks again for the help ;)
